import { useEffect, useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { useLocation } from "wouter";
import { Check, ClipboardList, FileImage, LayoutDashboard, MessageSquareQuote, Plus, Save, ShieldAlert, Sparkles, Trash2, Users } from "lucide-react";

const tabs = [
  { key: "overview", label: "نظرة عامة", icon: LayoutDashboard },
  { key: "services", label: "الخدمات", icon: Sparkles },
  { key: "projects", label: "الأعمال", icon: FileImage },
  { key: "reviews", label: "التقييمات", icon: MessageSquareQuote },
  { key: "leads", label: "الطلبات", icon: ClipboardList },
] as const;
type TabKey = typeof tabs[number]["key"];

function StatCard({ label, value, note, icon: Icon }: { label: string; value: number; note: string; icon: typeof Users }) {
  return <div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="h-5 w-5" /></span><strong className="text-3xl font-bold tracking-tight">{value}</strong></div><p className="mt-5 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>;
}

export default function Dashboard() {
  const [location, setLocation] = useLocation();
  const queryTab = new URLSearchParams(location.split("?")[1] || "").get("tab") as TabKey | null;
  const [activeTab, setActiveTab] = useState<TabKey>(queryTab && tabs.some(tab => tab.key === queryTab) ? queryTab : "overview");
  useEffect(() => { if (queryTab && tabs.some(tab => tab.key === queryTab)) setActiveTab(queryTab); }, [queryTab]);
  const selectTab = (tab: TabKey) => { setActiveTab(tab); setLocation(tab === "overview" ? "/dashboard" : `/dashboard?tab=${tab}`); };
  const overview = trpc.admin.overview.useQuery();
  const services = trpc.admin.services.useQuery(undefined, { enabled: activeTab === "services" });
  const projects = trpc.admin.projects.useQuery(undefined, { enabled: activeTab === "projects" });
  const reviews = trpc.admin.reviews.useQuery(undefined, { enabled: activeTab === "reviews" });
  const leads = trpc.admin.leads.useQuery(undefined, { enabled: activeTab === "leads" });
  const utils = trpc.useUtils();
  const createService = trpc.admin.createService.useMutation({ onSuccess: async () => { toast.success("تمت إضافة الخدمة"); await utils.admin.services.invalidate(); }, onError: e => toast.error(e.message) });
  const deleteService = trpc.admin.deleteService.useMutation({ onSuccess: async () => { toast.success("تم حذف الخدمة"); await utils.admin.services.invalidate(); }, onError: e => toast.error(e.message) });
  const publishReview = trpc.admin.setReviewPublished.useMutation({ onSuccess: async () => { await utils.admin.reviews.invalidate(); }, onError: e => toast.error(e.message) });
  const updateLead = trpc.admin.updateLeadStatus.useMutation({ onSuccess: async () => { toast.success("تم تحديث حالة الطلب"); await utils.admin.leads.invalidate(); await utils.admin.overview.invalidate(); }, onError: e => toast.error(e.message) });

  const isForbidden = overview.error?.data?.code === "FORBIDDEN";
  return <DashboardLayout>
    <div dir="rtl" className="min-h-screen bg-muted/20 p-2 sm:p-6">
      <div className="mx-auto max-w-7xl space-y-7">
        <header className="flex flex-col justify-between gap-4 rounded-3xl bg-gradient-to-l from-primary to-teal-700 p-6 text-primary-foreground shadow-lg sm:flex-row sm:items-end sm:p-8">
          <div><p className="mb-2 text-sm font-medium text-primary-foreground/70">لوحة تحكم همة الخليج</p><h1 className="text-3xl font-black tracking-tight sm:text-4xl">إدارة الموقع من مكان واحد.</h1><p className="mt-3 max-w-xl text-sm leading-7 text-primary-foreground/80">أدر الخدمات والأعمال والتقييمات وطلبات العملاء مع صلاحيات المدير.</p></div>
          <a href="/" className="inline-flex items-center justify-center rounded-xl border border-white/30 px-4 py-2 text-sm font-bold transition hover:bg-white/10">مشاهدة الموقع العام</a>
        </header>
        {isForbidden ? <div className="flex items-center gap-4 rounded-2xl border border-destructive/20 bg-destructive/5 p-5 text-destructive"><ShieldAlert className="h-6 w-6" /><div><h2 className="font-bold">لا تملك صلاحية الوصول</h2><p className="mt-1 text-sm">تسجيل الدخول مطلوب بحساب مدير الموقع.</p></div></div> : <>
          <nav className="flex gap-2 overflow-x-auto rounded-2xl border bg-card p-2 shadow-sm" aria-label="أقسام لوحة التحكم">{tabs.map(tab => <button key={tab.key} onClick={() => selectTab(tab.key)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold transition ${activeTab === tab.key ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-muted"}`}><tab.icon className="h-4 w-4" />{tab.label}</button>)}</nav>
          {activeTab === "overview" && <Overview data={overview.data} onOpen={selectTab} />}
          {activeTab === "services" && <ServicesPanel data={services.data ?? []} onCreate={input => createService.mutate(input)} onDelete={id => deleteService.mutate({ id })} busy={createService.isPending} />}
          {activeTab === "projects" && <ProjectsPanel data={projects.data ?? []} />}
          {activeTab === "reviews" && <ReviewsPanel data={reviews.data ?? []} onPublish={(id, isPublished) => publishReview.mutate({ id, isPublished })} />}
          {activeTab === "leads" && <LeadsPanel data={leads.data ?? []} onStatus={(id, status) => updateLead.mutate({ id, status })} />}
        </>}
      </div>
    </div>
  </DashboardLayout>;
}

function Overview({ data, onOpen }: { data?: { services: number; projects: number; reviews: number; leads: number; newLeads: number }; onOpen: (tab: TabKey) => void }) {
  const stats = data ?? { services: 0, projects: 0, reviews: 0, leads: 0, newLeads: 0 };
  return <section className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="الخدمات المنشورة" value={stats.services} note="يمكن تعديلها من قسم الخدمات" icon={Sparkles} /><StatCard label="الأعمال" value={stats.projects} note="صور وفيديوهات الموقع" icon={FileImage} /><StatCard label="التقييمات" value={stats.reviews} note="تحتاج مراجعة قبل النشر" icon={MessageSquareQuote} /><StatCard label="طلبات جديدة" value={stats.newLeads} note={`من أصل ${stats.leads} طلب`} icon={ClipboardList} /></div><div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">ابدأ بإدارة محتوى الموقع</h2><p className="mt-2 text-sm text-muted-foreground">أضف خدماتك الفعلية، ثم راجع التقييمات قبل إظهارها للزوار.</p></div><Users className="h-9 w-9 text-primary/50" /></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><button onClick={() => onOpen("services")} className="rounded-xl border p-4 text-right transition hover:border-primary hover:bg-primary/5"><Sparkles className="mb-4 h-5 w-5 text-primary" /><b className="block text-sm">إدارة الخدمات</b><span className="mt-1 block text-xs text-muted-foreground">أسماء ووصف وصور</span></button><button onClick={() => onOpen("reviews")} className="rounded-xl border p-4 text-right transition hover:border-primary hover:bg-primary/5"><MessageSquareQuote className="mb-4 h-5 w-5 text-primary" /><b className="block text-sm">مراجعة التقييمات</b><span className="mt-1 block text-xs text-muted-foreground">نشر أو إخفاء</span></button><button onClick={() => onOpen("leads")} className="rounded-xl border p-4 text-right transition hover:border-primary hover:bg-primary/5"><ClipboardList className="mb-4 h-5 w-5 text-primary" /><b className="block text-sm">متابعة الطلبات</b><span className="mt-1 block text-xs text-muted-foreground">تحديث الحالة</span></button></div></div><div className="rounded-2xl bg-foreground p-6 text-background shadow-sm"><p className="text-sm text-background/60">حالة الحساب</p><h2 className="mt-3 text-2xl font-black">محمي بصلاحية مدير</h2><div className="mt-6 flex items-center gap-2 text-sm text-background/75"><Check className="h-4 w-4 text-primary" /> لا يمكن للزوار الوصول للوحة</div><div className="mt-3 flex items-center gap-2 text-sm text-background/75"><Check className="h-4 w-4 text-primary" /> التقييمات لا تنشر تلقائيًا</div></div></div></section>;
}

function ServicesPanel({ data, onCreate, onDelete, busy }: { data: Array<{ id: number; title: string; description: string; imageUrl: string | null; isActive: number }>; onCreate: (input: { title: string; description: string; imageUrl?: string | null; iconKey: string; sortOrder: number; isActive: boolean }) => void; onDelete: (id: number) => void; busy: boolean }) {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [imageUrl, setImageUrl] = useState("");
  return <section className="grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><form onSubmit={e => { e.preventDefault(); if (!title || !description) return; onCreate({ title, description, imageUrl: imageUrl || null, iconKey: "sparkles", sortOrder: data.length, isActive: true }); setTitle(""); setDescription(""); setImageUrl(""); }} className="h-fit rounded-2xl border bg-card p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-3 text-primary"><Plus className="h-5 w-5" /></span><div><h2 className="font-bold">إضافة خدمة</h2><p className="text-xs text-muted-foreground">تظهر لاحقًا في محتوى الموقع</p></div></div><label className="mb-4 block text-sm font-semibold">اسم الخدمة<input value={title} onChange={e => setTitle(e.target.value)} className="mt-2 w-full rounded-xl border bg-background px-3 py-3 text-sm outline-none ring-primary/30 focus:ring-2" placeholder="مثال: تنظيف احترافي" /></label><label className="mb-4 block text-sm font-semibold">الوصف<textarea value={description} onChange={e => setDescription(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border bg-background px-3 py-3 text-sm outline-none ring-primary/30 focus:ring-2" placeholder="اكتب وصفًا واضحًا للخدمة" /></label><label className="mb-5 block text-sm font-semibold">رابط الصورة<input value={imageUrl} onChange={e => setImageUrl(e.target.value)} className="mt-2 w-full rounded-xl border bg-background px-3 py-3 text-sm outline-none ring-primary/30 focus:ring-2" placeholder="/manus-storage/..." /></label><button disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground transition hover:opacity-90 disabled:opacity-50"><Save className="h-4 w-4" />{busy ? "جارٍ الحفظ..." : "حفظ الخدمة"}</button></form><div className="space-y-3">{data.length === 0 ? <EmptyState text="لا توجد خدمات في قاعدة البيانات بعد. أضف أول خدمة من النموذج." /> : data.map(item => <article key={item.id} className="flex items-start gap-4 rounded-2xl border bg-card p-4 shadow-sm"><div className="h-16 w-20 shrink-0 overflow-hidden rounded-xl bg-muted">{item.imageUrl ? <img src={item.imageUrl} alt="" className="h-full w-full object-cover" /> : <Sparkles className="m-5 text-primary" />}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="font-bold">{item.title}</h3>{item.isActive === 1 && <span className="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-700">نشطة</span>}</div><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{item.description}</p></div><button onClick={() => onDelete(item.id)} className="rounded-lg p-2 text-muted-foreground transition hover:bg-destructive/10 hover:text-destructive" aria-label={`حذف ${item.title}`}><Trash2 className="h-4 w-4" /></button></article>)}</div></section>;
}

function ProjectsPanel({ data }: { data: Array<{ id: number; title: string; label: string | null; mediaUrl: string; mediaType: "image" | "video"; isActive: number }> }) { return <section className="rounded-2xl border bg-card p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">الأعمال المنشورة</h2><p className="mt-1 text-sm text-muted-foreground">الوسائط التي يمكن ربطها بالصفحة العامة.</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{data.length} أعمال</span></div>{data.length === 0 ? <EmptyState text="لا توجد أعمال في قاعدة البيانات بعد. يمكنك إضافة المشاريع لاحقًا من نفس اللوحة." /> : <div className="grid gap-4 sm:grid-cols-2">{data.map(item => <article key={item.id} className="overflow-hidden rounded-2xl border"><div className="aspect-video bg-muted">{item.mediaType === "video" ? <video src={item.mediaUrl} controls className="h-full w-full object-cover" /> : <img src={item.mediaUrl} alt={item.title} className="h-full w-full object-cover" />}</div><div className="p-4"><h3 className="font-bold">{item.title}</h3><p className="mt-1 text-xs text-muted-foreground">{item.label}</p></div></article>)}</div>}</section>; }

function ReviewsPanel({ data, onPublish }: { data: Array<{ id: number; customerName: string; body: string; rating: number; isPublished: number }>; onPublish: (id: number, isPublished: boolean) => void }) { return <section className="space-y-3">{data.length === 0 ? <EmptyState text="لا توجد تقييمات مستلمة بعد. ستظهر هنا لمراجعتها قبل النشر." /> : data.map(item => <article key={item.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-3"><h3 className="font-bold">{item.customerName}</h3><span className="text-sm text-amber-500">{"★".repeat(item.rating)}</span></div><p className="mt-3 leading-7 text-muted-foreground">{item.body}</p></div><button onClick={() => onPublish(item.id, item.isPublished !== 1)} className={`shrink-0 rounded-xl px-4 py-2 text-sm font-bold ${item.isPublished === 1 ? "bg-emerald-100 text-emerald-700" : "bg-primary text-primary-foreground"}`}>{item.isPublished === 1 ? "منشور" : "مراجعة ونشر"}</button></div></article>)}</section>; }

function LeadsPanel({ data, onStatus }: { data: Array<{ id: number; customerName: string; phone: string; service: string | null; message: string | null; status: "new" | "contacted" | "closed" }>; onStatus: (id: number, status: "new" | "contacted" | "closed") => void }) { return <section className="rounded-2xl border bg-card shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-bold">طلبات التواصل</h2><p className="mt-1 text-sm text-muted-foreground">تابع الطلبات الواردة وحدث حالتها بعد التواصل.</p></div>{data.length === 0 ? <EmptyState text="لا توجد طلبات مسجلة بعد." /> : <div className="divide-y">{data.map(item => <article key={item.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold">{item.customerName}</h3><a href={`tel:${item.phone}`} className="mt-1 block text-sm text-primary">{item.phone}</a><p className="mt-1 text-xs text-muted-foreground">{item.service || "استفسار عام"}{item.message ? ` — ${item.message}` : ""}</p></div><select value={item.status} onChange={e => onStatus(item.id, e.target.value as "new" | "contacted" | "closed")} className="rounded-xl border bg-background px-3 py-2 text-sm font-bold"><option value="new">جديد</option><option value="contacted">تم التواصل</option><option value="closed">مغلق</option></select></article>)}</div>}</section>; }

function EmptyState({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed bg-card p-10 text-center text-sm text-muted-foreground"><MessageSquareQuote className="mx-auto mb-3 h-8 w-8 text-primary/50" />{text}</div>; }
